import {
  type ConfigFieldDefinition,
  type ConfigFieldGroup,
} from "@/types/config";
import { DEFAULT_EVENT_GRID_RING_COUNT } from "@/lib/simulation/events";

export const CURRENT_SCHEMA_VERSION = 3;
export const DEFAULT_SIMULATION_SEED = 20260405;

const buildNumberField = (
  definition: Omit<
    Extract<ConfigFieldDefinition, { valueType: "number" }>,
    "scope" | "version"
  >,
): ConfigFieldDefinition => ({
  scope: "simulation",
  version: CURRENT_SCHEMA_VERSION,
  ...definition,
});

const buildSelectField = (
  definition: Omit<
    Extract<ConfigFieldDefinition, { valueType: "select" }>,
    "scope" | "version"
  >,
): ConfigFieldDefinition => ({
  scope: "simulation",
  version: CURRENT_SCHEMA_VERSION,
  ...definition,
});

export const simulationFieldDefinitions: ConfigFieldDefinition[] = [
  buildNumberField({
    id: "agentCount",
    group: "population",
    label: "Agent Count",
    description: "Total number of agents in the simulation.",
    targetPath: "population.agentCount",
    applyMode: "draft-reset",
    visible: true,
    valueType: "number",
    defaultValue: 1000,
    min: 100,
    max: 5000,
    step: 100,
    integer: true,
    normalize: { clamp: true, roundToStep: true, precision: 2 },
    unit: "agents",
  }),
  buildNumberField({
    id: "initialWealth",
    group: "population",
    label: "Initial Wealth",
    description: "Equal starting wealth given to every agent in the baseline world.",
    targetPath: "population.initialWealth",
    applyMode: "draft-reset",
    visible: true,
    valueType: "number",
    defaultValue: 10,
    min: 0,
    max: 1000,
    step: 1,
    normalize: { clamp: true, roundToStep: true, precision: 2 },
    unit: "currency",
  }),
  buildNumberField({
    id: "wealthFloor",
    group: "population",
    label: "Wealth Floor",
    description: "Minimum possible wealth after loss events.",
    targetPath: "population.wealthFloor",
    applyMode: "draft-reset",
    visible: true,
    valueType: "number",
    defaultValue: 0,
    min: 0,
    max: 1000,
    step: 10,
    normalize: { clamp: true, roundToStep: true, precision: 2 },
    unit: "currency",
  }),
  buildNumberField({
    id: "agentRadius",
    group: "population",
    label: "Agent Radius",
    description: "Visual and collision radius for agents.",
    targetPath: "population.agentRadius",
    applyMode: "draft-reset",
    visible: true,
    valueType: "number",
    defaultValue: 3,
    min: 1,
    max: 12,
    step: 1,
    integer: true,
    normalize: { clamp: true, roundToStep: true, precision: 2 },
    unit: "px",
  }),
  buildNumberField({
    id: "arenaWidth",
    group: "arena",
    label: "Arena Width",
    description: "Width of the simulation arena.",
    targetPath: "arena.width",
    applyMode: "draft-reset",
    visible: true,
    valueType: "number",
    defaultValue: 1200,
    min: 400,
    max: 4000,
    step: 50,
    integer: true,
    normalize: { clamp: true, roundToStep: true },
    unit: "px",
  }),
  buildNumberField({
    id: "arenaHeight",
    group: "arena",
    label: "Arena Height",
    description: "Height of the simulation arena.",
    targetPath: "arena.height",
    applyMode: "draft-reset",
    visible: true,
    valueType: "number",
    defaultValue: 800,
    min: 300,
    max: 3000,
    step: 50,
    integer: true,
    normalize: { clamp: true, roundToStep: true },
    unit: "px",
  }),
  buildNumberField({
    id: "agentSpeed",
    group: "movement",
    label: "Agent Speed",
    description: "Base movement speed for agents.",
    targetPath: "movement.agentSpeed",
    applyMode: "draft-reset",
    visible: true,
    valueType: "number",
    defaultValue: 8,
    min: 0.1,
    max: 20,
    step: 0.1,
    normalize: { clamp: true, roundToStep: true, precision: 2 },
    unit: "units",
  }),
  buildNumberField({
    id: "eventSpeed",
    group: "movement",
    label: "Event Drift",
    description: "How much luck and bad luck dots move. Baseline keeps them fixed.",
    targetPath: "movement.eventSpeed",
    applyMode: "draft-reset",
    visible: true,
    valueType: "number",
    defaultValue: 0,
    min: 0,
    max: 10,
    step: 0.1,
    normalize: { clamp: true, roundToStep: true, precision: 2 },
    unit: "units",
  }),
  buildSelectField({
    id: "speedProfile",
    group: "movement",
    label: "Speed Profile",
    description: "Preset profile for interpreting the speed values.",
    targetPath: "movement.speedProfile",
    applyMode: "draft-reset",
    visible: true,
    valueType: "select",
    defaultValue: "normal",
    options: [
      { label: "Slow", value: "slow" },
      { label: "Normal", value: "normal" },
      { label: "Fast", value: "fast" },
    ],
  }),
  buildNumberField({
    id: "gridRingCount",
    group: "events",
    label: "Event Grid Rings",
    description: "Adds or removes the event cluster one outer grid ring at a time.",
    targetPath: "events.gridRingCount",
    applyMode: "draft-reset",
    visible: true,
    valueType: "number",
    defaultValue: DEFAULT_EVENT_GRID_RING_COUNT,
    min: 0,
    max: 12,
    step: 1,
    integer: true,
    normalize: { clamp: true, roundToStep: true },
    unit: "rings",
  }),
  buildNumberField({
    id: "luckSharePercent",
    group: "events",
    label: "Green Dot Share",
    description: "Share of the current event grid that is green. The ring setting changes total dots, while this controls the color split.",
    targetPath: "events.luckSharePercent",
    applyMode: "draft-reset",
    visible: true,
    valueType: "number",
    defaultValue: 40,
    min: 0,
    max: 100,
    step: 5,
    integer: true,
    normalize: { clamp: true, roundToStep: true },
    unit: "%",
  }),
  buildNumberField({
    id: "luckyGainBase",
    group: "events",
    label: "Lucky Success Multiplier",
    description: "How strongly wealth grows when an agent catches a lucky opportunity.",
    targetPath: "events.luckyGainBase",
    applyMode: "draft-reset",
    visible: true,
    valueType: "number",
    defaultValue: 2,
    min: 1,
    max: 5,
    step: 0.1,
    normalize: { clamp: true, roundToStep: true },
    unit: "x",
  }),
  buildNumberField({
    id: "unluckyLossBase",
    group: "events",
    label: "Bad Luck Multiplier",
    description: "How much wealth remains after a bad luck collision.",
    targetPath: "events.unluckyLossBase",
    applyMode: "draft-reset",
    visible: true,
    valueType: "number",
    defaultValue: 0.5,
    min: 0,
    max: 1,
    step: 0.05,
    normalize: { clamp: true, roundToStep: true },
    unit: "x",
  }),
  buildNumberField({
    id: "yearInterval",
    group: "economy",
    label: "Year Interval",
    description: "Number of steps that represent a yearly capital return cycle.",
    targetPath: "economy.yearInterval",
    applyMode: "draft-reset",
    visible: true,
    valueType: "number",
    defaultValue: 20,
    min: 1,
    max: 1000,
    step: 1,
    integer: true,
    normalize: { clamp: true, roundToStep: true },
    unit: "steps",
  }),
  buildNumberField({
    id: "capitalReturnBase",
    group: "economy",
    label: "Capital Return",
    description: "Optional background compounding. Leave at zero for the pure baseline model.",
    targetPath: "economy.capitalReturnBase",
    applyMode: "draft-reset",
    visible: true,
    valueType: "number",
    defaultValue: 0,
    min: 0,
    max: 0.2,
    step: 0.005,
    normalize: { clamp: true, roundToStep: true, precision: 3 },
    unit: "ratio",
  }),
  buildNumberField({
    id: "talentReturnBonus",
    group: "economy",
    label: "Talent Return Bonus",
    description: "Optional extra compounding from talent. Leave at zero for the pure baseline model.",
    targetPath: "economy.talentReturnBonus",
    applyMode: "draft-reset",
    visible: true,
    valueType: "number",
    defaultValue: 0,
    min: 0,
    max: 1,
    step: 0.01,
    normalize: { clamp: true, roundToStep: true, precision: 3 },
    unit: "ratio",
  }),
  buildNumberField({
    id: "comfortableWealth",
    group: "happiness",
    label: "Comfortable Wealth",
    description: "Wealth level where security contribution saturates.",
    targetPath: "happiness.comfortableWealth",
    applyMode: "draft-reset",
    visible: true,
    valueType: "number",
    defaultValue: 20,
    min: 1,
    max: 5000,
    step: 1,
    normalize: { clamp: true, roundToStep: true },
    unit: "currency",
  }),
  buildNumberField({
    id: "trendClamp",
    group: "happiness",
    label: "Trend Clamp",
    description: "Clamp value used for recent wealth delta normalization.",
    targetPath: "happiness.trendClamp",
    applyMode: "draft-reset",
    visible: true,
    valueType: "number",
    defaultValue: 10,
    min: 1,
    max: 500,
    step: 1,
    normalize: { clamp: true, roundToStep: true },
    unit: "currency",
  }),
  buildNumberField({
    id: "bankruptcyPenalty",
    group: "happiness",
    label: "Bankruptcy Penalty",
    description: "Penalty applied to happiness when wealth hits the floor.",
    targetPath: "happiness.bankruptcyPenalty",
    applyMode: "draft-reset",
    visible: true,
    valueType: "number",
    defaultValue: 0.15,
    min: 0,
    max: 1,
    step: 0.01,
    normalize: { clamp: true, roundToStep: true, precision: 2 },
    unit: "ratio",
  }),
];

export const configFieldGroups: ConfigFieldGroup[] = [
  "population",
  "arena",
  "movement",
  "events",
  "economy",
  "happiness",
  "policies",
  "advanced",
];

export function getConfigFieldDefinitions(): ConfigFieldDefinition[] {
  return simulationFieldDefinitions.map((field) => ({ ...field }));
}

export function getConfigFieldDefinitionById(
  fieldId: string,
): ConfigFieldDefinition | undefined {
  return simulationFieldDefinitions.find((field) => field.id === fieldId);
}
