import type {
  ComposerBlock,
  ComposerBlockDefinition,
  ComposerConditionBlock,
  ComposerEffectBlock,
  ComposerModifierBlock,
  ComposerTargetBlock,
} from "@/types/composer";

const targetDefinitions: ComposerBlockDefinition<ComposerTargetBlock>[] = [
  {
    type: "allAgents",
    category: "target",
    label: "All Agents",
    description: "Apply the rule to the whole population.",
    parameters: [],
    defaultPayload: {},
    allowsMultiplePerRule: false,
    sortOrder: 10,
  },
  {
    type: "bottomWealthPercent",
    category: "target",
    label: "Bottom Wealth Percent",
    description: "Target the poorest share of the population.",
    parameters: [
      {
        key: "percent",
        label: "Percent",
        description: "Population share to include.",
        valueType: "number",
        min: 1,
        max: 100,
        step: 1,
      },
    ],
    defaultPayload: { percent: 25 },
    allowsMultiplePerRule: false,
    sortOrder: 20,
  },
  {
    type: "topWealthPercent",
    category: "target",
    label: "Top Wealth Percent",
    description: "Target the richest share of the population.",
    parameters: [
      {
        key: "percent",
        label: "Percent",
        description: "Population share to include.",
        valueType: "number",
        min: 1,
        max: 100,
        step: 1,
      },
    ],
    defaultPayload: { percent: 10 },
    allowsMultiplePerRule: false,
    sortOrder: 30,
  },
  {
    type: "wealthBelow",
    category: "target",
    label: "Wealth Below",
    description: "Target agents under a wealth threshold.",
    parameters: [
      {
        key: "threshold",
        label: "Threshold",
        description: "Maximum wealth allowed into the target set.",
        valueType: "number",
        min: 0,
        max: 100000,
        step: 1,
      },
    ],
    defaultPayload: { threshold: 50 },
    allowsMultiplePerRule: false,
    sortOrder: 40,
  },
  {
    type: "wealthAbove",
    category: "target",
    label: "Wealth Above",
    description: "Target agents above a wealth threshold.",
    parameters: [
      {
        key: "threshold",
        label: "Threshold",
        description: "Minimum wealth required for inclusion.",
        valueType: "number",
        min: 0,
        max: 100000,
        step: 1,
      },
    ],
    defaultPayload: { threshold: 250 },
    allowsMultiplePerRule: false,
    sortOrder: 50,
  },
  {
    type: "talentAbove",
    category: "target",
    label: "Talent Above",
    description: "Target agents with talent above a threshold.",
    parameters: [
      {
        key: "threshold",
        label: "Threshold",
        description: "Minimum talent required.",
        valueType: "number",
        min: 0,
        max: 1,
        step: 0.01,
      },
    ],
    defaultPayload: { threshold: 0.75 },
    allowsMultiplePerRule: false,
    sortOrder: 60,
  },
  {
    type: "highTalentLowWealth",
    category: "target",
    label: "High Talent + Low Wealth",
    description: "Target talented agents that remain poor.",
    parameters: [
      {
        key: "talentThreshold",
        label: "Talent Threshold",
        description: "Minimum talent required.",
        valueType: "number",
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        key: "wealthCeiling",
        label: "Wealth Ceiling",
        description: "Maximum wealth allowed.",
        valueType: "number",
        min: 0,
        max: 100000,
        step: 1,
      },
    ],
    defaultPayload: { talentThreshold: 0.8, wealthCeiling: 120 },
    allowsMultiplePerRule: false,
    sortOrder: 70,
  },
  {
    type: "bankruptAgents",
    category: "target",
    label: "Previously Bankrupt Agents",
    description: "Target agents with a bankruptcy history.",
    parameters: [
      {
        key: "minBankruptCount",
        label: "Minimum Bankrupt Count",
        description: "Minimum bankruptcy count required.",
        valueType: "number",
        min: 1,
        max: 100,
        step: 1,
      },
    ],
    defaultPayload: { minBankruptCount: 1 },
    allowsMultiplePerRule: false,
    sortOrder: 80,
  },
];

const conditionDefinitions: ComposerBlockDefinition<ComposerConditionBlock>[] = [
  {
    type: "wealthBelow",
    category: "condition",
    label: "Condition: Wealth Below",
    description: "Keep only agents whose wealth is below the threshold.",
    parameters: [
      {
        key: "threshold",
        label: "Threshold",
        description: "Maximum wealth allowed.",
        valueType: "number",
        min: 0,
        max: 100000,
        step: 1,
      },
    ],
    defaultPayload: { threshold: 75 },
    sortOrder: 10,
  },
  {
    type: "wealthAbove",
    category: "condition",
    label: "Condition: Wealth Above",
    description: "Keep only agents whose wealth is above the threshold.",
    parameters: [
      {
        key: "threshold",
        label: "Threshold",
        description: "Minimum wealth required.",
        valueType: "number",
        min: 0,
        max: 100000,
        step: 1,
      },
    ],
    defaultPayload: { threshold: 200 },
    sortOrder: 20,
  },
  {
    type: "talentBelow",
    category: "condition",
    label: "Condition: Talent Below",
    description: "Keep only agents whose talent is below the threshold.",
    parameters: [
      {
        key: "threshold",
        label: "Threshold",
        description: "Maximum talent allowed.",
        valueType: "number",
        min: 0,
        max: 1,
        step: 0.01,
      },
    ],
    defaultPayload: { threshold: 0.5 },
    sortOrder: 30,
  },
  {
    type: "talentAbove",
    category: "condition",
    label: "Condition: Talent Above",
    description: "Keep only agents whose talent is above the threshold.",
    parameters: [
      {
        key: "threshold",
        label: "Threshold",
        description: "Minimum talent required.",
        valueType: "number",
        min: 0,
        max: 1,
        step: 0.01,
      },
    ],
    defaultPayload: { threshold: 0.7 },
    sortOrder: 40,
  },
  {
    type: "rescuedCountBelow",
    category: "condition",
    label: "Condition: Rescue Count Below",
    description: "Keep only agents with rescue counts below the cap.",
    parameters: [
      {
        key: "maxRescuedCount",
        label: "Max Rescued Count",
        description: "Maximum rescue count allowed.",
        valueType: "number",
        min: 0,
        max: 100,
        step: 1,
      },
    ],
    defaultPayload: { maxRescuedCount: 2 },
    sortOrder: 50,
  },
  {
    type: "bankruptCountAtLeast",
    category: "condition",
    label: "Condition: Bankrupt Count At Least",
    description: "Keep only agents with at least this many bankruptcies.",
    parameters: [
      {
        key: "minBankruptCount",
        label: "Minimum Bankrupt Count",
        description: "Minimum bankruptcy count required.",
        valueType: "number",
        min: 0,
        max: 100,
        step: 1,
      },
    ],
    defaultPayload: { minBankruptCount: 1 },
    sortOrder: 60,
  },
];

const effectDefinitions: ComposerBlockDefinition<ComposerEffectBlock>[] = [
  {
    type: "grantAmount",
    category: "effect",
    label: "Grant Fixed Amount",
    description: "Give selected agents a direct transfer.",
    parameters: [
      {
        key: "amount",
        label: "Amount",
        description: "Transfer amount.",
        valueType: "number",
        min: 0,
        max: 10000,
        step: 1,
      },
    ],
    defaultPayload: { amount: 10 },
    sortOrder: 10,
  },
  {
    type: "wealthTax",
    category: "effect",
    label: "Apply Wealth Tax",
    description: "Tax selected agents above a threshold.",
    parameters: [
      {
        key: "threshold",
        label: "Threshold",
        description: "Taxable wealth begins above this value.",
        valueType: "number",
        min: 0,
        max: 100000,
        step: 1,
      },
      {
        key: "rate",
        label: "Rate",
        description: "Marginal tax rate.",
        valueType: "number",
        min: 0,
        max: 1,
        step: 0.01,
      },
    ],
    defaultPayload: { threshold: 300, rate: 0.05 },
    allowedRuleCadences: ["year"],
    sortOrder: 20,
  },
  {
    type: "progressiveTax",
    category: "effect",
    label: "Apply Progressive Tax",
    description: "Tax selected agents using progressive brackets.",
    parameters: [],
    defaultPayload: {
      brackets: [
        { threshold: 200, rate: 0.05 },
        { threshold: 400, rate: 0.1 },
      ],
    },
    allowedRuleCadences: ["year"],
    sortOrder: 25,
  },
  {
    type: "setWealthFloor",
    category: "effect",
    label: "Set Wealth Floor",
    description: "Raise selected agents up to a minimum wealth level.",
    parameters: [
      {
        key: "minimumWealth",
        label: "Minimum Wealth",
        description: "Target floor level.",
        valueType: "number",
        min: 0,
        max: 10000,
        step: 1,
      },
    ],
    defaultPayload: { minimumWealth: 10 },
    allowedRuleCadences: ["step"],
    sortOrder: 30,
  },
  {
    type: "bailout",
    category: "effect",
    label: "Bailout",
    description: "Rescue selected agents under a trigger wealth until the limit is used.",
    parameters: [
      {
        key: "triggerWealth",
        label: "Trigger Wealth",
        description: "Agents at or below this wealth can be rescued.",
        valueType: "number",
        min: 0,
        max: 10000,
        step: 1,
      },
      {
        key: "amount",
        label: "Amount",
        description: "Relief amount per rescue.",
        valueType: "number",
        min: 0,
        max: 10000,
        step: 1,
      },
      {
        key: "maxPerAgent",
        label: "Max Per Agent",
        description: "Maximum bailout count per agent.",
        valueType: "number",
        min: 1,
        max: 100,
        step: 1,
      },
    ],
    defaultPayload: { triggerWealth: 0, amount: 8, maxPerAgent: 3 },
    allowedRuleCadences: ["step"],
    sortOrder: 40,
  },
  {
    type: "talentGrant",
    category: "effect",
    label: "Talent Grant",
    description: "Grant high-talent, low-wealth selected agents a targeted subsidy.",
    parameters: [
      {
        key: "talentThreshold",
        label: "Talent Threshold",
        description: "Minimum talent required.",
        valueType: "number",
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        key: "wealthCeiling",
        label: "Wealth Ceiling",
        description: "Maximum wealth allowed.",
        valueType: "number",
        min: 0,
        max: 100000,
        step: 1,
      },
      {
        key: "amount",
        label: "Amount",
        description: "Grant amount per eligible agent.",
        valueType: "number",
        min: 0,
        max: 10000,
        step: 1,
      },
    ],
    defaultPayload: {
      talentThreshold: 0.8,
      wealthCeiling: 120,
      amount: 20,
    },
    allowedRuleCadences: ["year"],
    sortOrder: 50,
  },
];

const modifierDefinitions: ComposerBlockDefinition<ComposerModifierBlock>[] = [
  {
    type: "budgetCap",
    category: "modifier",
    label: "Budget Cap",
    description: "Limit total positive spending for this rule.",
    parameters: [
      {
        key: "maxBudget",
        label: "Max Budget",
        description: "Maximum gross spending allowed.",
        valueType: "number",
        min: 0,
        max: 1000000,
        step: 1,
      },
    ],
    defaultPayload: { maxBudget: 1000 },
    sortOrder: 10,
  },
  {
    type: "maxRecipients",
    category: "modifier",
    label: "Max Recipients",
    description: "Stop after this many selected agents receive the effect.",
    parameters: [
      {
        key: "count",
        label: "Count",
        description: "Maximum selected agents to affect.",
        valueType: "number",
        min: 1,
        max: 100000,
        step: 1,
      },
    ],
    defaultPayload: { count: 100 },
    sortOrder: 20,
  },
  {
    type: "weightMultiplier",
    category: "modifier",
    label: "Weight Multiplier",
    description: "Multiply the effect magnitude by this factor.",
    parameters: [
      {
        key: "value",
        label: "Value",
        description: "Effect multiplier.",
        valueType: "number",
        min: 0,
        max: 100,
        step: 0.1,
      },
    ],
    defaultPayload: { value: 1 },
    sortOrder: 30,
  },
  {
    type: "priorityScoreWeight",
    category: "modifier",
    label: "Priority Score Weight",
    description: "Sort selected agents by weighted talent, wealth, and bankruptcy score.",
    parameters: [
      {
        key: "talentWeight",
        label: "Talent Weight",
        description: "Weight for talent in the priority score.",
        valueType: "number",
        min: -100,
        max: 100,
        step: 0.1,
      },
      {
        key: "wealthWeight",
        label: "Wealth Weight",
        description: "Weight for normalized wealth in the priority score.",
        valueType: "number",
        min: -100,
        max: 100,
        step: 0.1,
      },
      {
        key: "bankruptWeight",
        label: "Bankrupt Weight",
        description: "Weight for bankruptcy history in the priority score.",
        valueType: "number",
        min: -100,
        max: 100,
        step: 0.1,
      },
    ],
    defaultPayload: { talentWeight: 1, wealthWeight: -1, bankruptWeight: 2 },
    sortOrder: 40,
  },
];

export const composerRegistry = {
  targets: targetDefinitions,
  conditions: conditionDefinitions,
  effects: effectDefinitions,
  modifiers: modifierDefinitions,
} as const;

export function getComposerBlockDefinitions(): ComposerBlockDefinition[] {
  return [
    ...targetDefinitions,
    ...conditionDefinitions,
    ...effectDefinitions,
    ...modifierDefinitions,
  ].sort((left, right) => left.sortOrder - right.sortOrder);
}

export function getComposerBlockDefinition(
  type: ComposerBlock["type"],
  category?: ComposerBlock["category"],
): ComposerBlockDefinition | undefined {
  const matches = getComposerBlockDefinitions().filter(
    (definition) => definition.type === type,
  );

  if (category) {
    return matches.find((definition) => definition.category === category);
  }

  return matches.length === 1 ? matches[0] : undefined;
}
